import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react';

import MarkdownView from 'react-showdown';
import {Fragment} from 'react'
import {Disclosure, Menu, Transition} from '@headlessui/react'
import {Bars3Icon, BellIcon, XMarkIcon} from '@heroicons/react/24/outline'

import LoginBtn from '/pages/components/login-btn'
import Link from "next/link";
import {useEffect} from 'react'
import Navbar from "../components/navbar";
function GetRepos() {

    const [repos, setRepos] = useState(null)
    const [isLoading, setLoading] = useState(false)

    useEffect(() => {
        setLoading(true)
        fetch('/api/github/get-repos')
            .then((res) => res.json())
            .then(({data}) => {
                setRepos(data.repositories)
                setLoading(false)
            })
    }, [])

    if (isLoading) return <p>در حال دریافت مخازن شما...</p>
    if (!repos) return <p>به نظر می‌رسه مخزنی ندارید!</p>

    return (
        <div>
            {

                repos.map((repo, i) =>
                    <div key={i}
                         className="flex flex-row justify-between p-6 bg-white border border-gray-200 rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700 mb-5">
                        <a href="#">
                            <h3 className="mb-2 text-xl font-bold text-gray-900 dark:text-white">{repo.name}</h3>
                        </a>
                        <a href={`/repos/${repo.name}`}
                           className="inline-flex items-center px-3 py-2 text-sm text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor"
                                 viewBox="0 0 20 20"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fillRule="evenodd"
                                      d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                                      clipRule="evenodd"></path>
                            </svg>
                            انتخاب مخزن
                        </a>
                    </div>
                )
            }
        </div>
    )
}
export default function Home() {

    const [markdown, setMarkdown] = useState('');


    return (
        <>
            <Head>
                <title>Mdown</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>

                <LoginBtn></LoginBtn>

                <Navbar></Navbar>

                <div className="pb-12">
                    <section className="pb-10">
                        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                            <div className='px-10 mt-10'>
                                <h2 className='font-bold text-2xl'>مخزن‌ها</h2>
                                <div className='mt-10 '>
                                    <GetRepos></GetRepos>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </>
    )
}
