import Head from 'next/head'
import {useState} from 'react';
import LoginBtn from '/components/login-btn'
import {useEffect} from 'react'
import Navbar from '/components/navbar'
import {useRouter} from 'next/router'
import GetContents from '/components/get-contents'

export default function Home() {


    const [markdown, setMarkdown] = useState(null);
    const [owner, setOwner] = useState('')
    const [repo, setRepo] = useState('')
    const [path, setPath] = useState('')
    const [data, setData] = useState(null)
    const [isLoading, setLoading] = useState(false)
    const router = useRouter()

    useEffect(() => {
        if (!router.query.repo)
            return
        setPath('')
        setLoading(true)
        setRepo(router.query.repo)
        setOwner(router.query.owner)
        router.query.path.map((item, index) => (setPath((prev) => (prev + '/' + item))))
    }, [router.query])


    return (
        <>
            <Head>
                <title>Mdown</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Navbar></Navbar>
                <div className="pb-12">
                    <section className="pb-10">
                        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                            <div className='px-10 mt-10'>
                                <h2 className='font-bold text-2xl'>شما در مخزن {repo} هستید </h2>
                                <h2 className='text-xl'>شما در مسیر {path} هستید </h2>

                                <div className='mt-10 '>
                                    <GetContents owner={owner} repo={repo} path={path}></GetContents>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </>
    )
}
