import Head from 'next/head'
import {useState} from 'react';
import Navbar from '/components/navbar'

export default function Home() {

    const [markdown, setMarkdown] = useState('');

    return (
        <>
            <Head>
                <title>Mdown</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>

                <Navbar></Navbar>
                <div className="pb-12">
                    <section className="pb-10">
                        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                            <div className='px-10 mt-10'>
                                <h2 className='font-bold text-2xl'>به مارک داون خوش آمدید</h2>
                                <div className='mt-10 bg-yellow-100 py-4 px-6'>
                                    <p>

                                        Markdown یک ابزار تبدیل متن به HTML برای نویسندگان وب است. Markdown به شما امکان
                                        می دهد با استفاده از یک قالب ساده برای خواندن و نوشتن آسان بنویسید ، سپس آن را
                                        به XHTML (یا HTML) معتبر ساختاری تبدیل کنید.


                                        <br/>

                                        Markdown در نظر گرفته شده است با عنوان آسان برای خواندن و آسان برای نوشتن به
                                        عنوان امکان پذیر است. با این حال، بر خوانایی بیش از هر چیز تأکید شده است. یک
                                        سند با فرمت Markdown باید همانطور که هست، به عنوان یک متن ساده، قابل انتشار
                                        باشد، بدون اینکه با برچسب ها یا دستورالعمل های قالب بندی مشخص شده باشد.

                                        <br/>
                                        برای این منظور ، نحو Markdown کاملاً از نکات نگارشی تشکیل شده است، که
                                        کاراکترهای نقطه گذاری با دقت انتخاب شده اند تا به معنی آنها برسند. به
                                        عنوان مثال ، ستاره های اطراف یک کلمه در واقع شبیه *تأکید* هستند. لیست
                                        های Markdown شبیه به لیست ها هستند. حتی با وجود فرض اینکه شما تا به حال
                                        از ایمیل استفاده کرده اید ، نقل قول های بلوک مانند متن های نقل قول شده
                                        به نظر می رسند.

                                        <br/>

                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </>
    )
}
