import Head from 'next/head'
import Image from 'next/image'
import {useState} from 'react';
import MarkdownView from 'react-showdown';
import LoginBtn from '/pages/components/login-btn'
import Link from "next/link";
import Navbar from './components/navbar'

export default function Home() {

    const [markdown, setMarkdown] = useState('');

    return (
        <>
            <Head>
                <title>Mdown</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>

                <Navbar></Navbar>

                <div className='flex flex-row mt-2 px-5'>

                    <div className='flex flex-1 px-5'>
                        <textarea className='w-full h-min-screen'
                                  onChange={(event) => (setMarkdown(event.target.value))}></textarea>
                    </div>
                    <div
                        className='flex flex-1 px-5 w-full h-screen navHeight_off overflow-y-scroll hidden flex-col flex-1 w-full py-4 bg-blue-100 md:flex border-r-4 border-blue-100 '>
                        <article className="prose lg:prose-xl w-full">
                            <MarkdownView
                                markdown={markdown}
                                options={{tables: true, emoji: true}}
                            />
                        </article>
                    </div>
                </div>

                <LoginBtn></LoginBtn>

            </main>
        </>
    )
}
