import Head from 'next/head'
import Navbar from './components/navbar'
import {signOut, useSession} from "next-auth/react"
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import Link from "next/link";

export default function InstallStatus() {


    const [status, setStatus] = useState(false)
    const [isLoading, setLoading] = useState(false)
    const router = useRouter()

    useEffect(() => {
        if (!router.query.status)
            return
        setLoading(true)
        setStatus(router.query.status)
        setLoading(false)
    }, [router.query])


    return (
        <>
            <Head>
                <title>Mdown</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>

                <Navbar></Navbar>

                <div className='flex flex-row mt-2 px-5'>
                    {
                        isLoading ?
                            <>loading ...</>
                            :
                            <>
                                {
                                    !status || status ==='nok' ?
                                        <>
                                            <div className='container mx-auto content-center items-center px-6 py-4'>
                                                <p className='text-xl'>به نظر می‌رسه مشکلی در نصب بات Mdown پیش آمده</p>
                                                <p className='text-xl'>لطفا مجددا امتحان کنید اما اگر باز هم درست نشد به پشتیبانی اطلاع بدید تا مشکل رو بررسی کنیم.</p>
                                            </div>

                                        </>
                                        :

                                        <>
                                            <div className='container mx-auto content-center items-center px-6 py-4'>
                                                <p className='text-xl'>نصب Mdown بر روی مخازن گیت‌هابی که مشخص کردید
                                                    انجام شد. حالا می‌توانید به صفحه گیت‌هاب بروید و مخازن را مشاهده
                                                    کنید و هر فایلی که می‌خواهید را ادیت کنید.</p>
                                                <hr className='my-10'/>
                                                <p className='text-xl'>در صورتی که قادر به مشاهده مخازن نیستید یا با
                                                    مشکلی مواجه هستید سعی کنید ربات mdown را یک بار از مخازن حذف کنید و
                                                    مجددا نصب کنید.
                                                    در صورتی که بازهم درست نشد به پشتیبانی اطلاع دهید تا مشکل را بررسی
                                                    کنیم.</p>
                                                <Link href='/repos'>
                                                    <button className="w-full mt-10 group h-12 px-6 border-2 border-gray-300 rounded-full transition duration-300
 hover:border-blue-400 focus:bg-blue-50 active:bg-blue-100">
                                                        <div
                                                            class="relative flex items-center space-x-4 justify-center">
                                                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                                                 className="absolute left-0 w-5 text-gray-700"
                                                                 viewBox="0 0 16 16">
                                                                <path
                                                                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                                                            </svg>
                                                            <span
                                                                class="block w-max font-semibold tracking-wide text-gray-700 text-sm transition duration-300 group-hover:text-blue-600 sm:text-base">مشاهده مخازن</span>
                                                        </div>
                                                    </button>
                                                </Link>
                                            </div>

                                        </>
                                }
                            </>
                    }
                </div>
            </main>
        </>
    )
}
