import Head from 'next/head'
import Navbar from '/components/navbar'

export default function MarkDown() {

    return (
        <>
            <Head>
                <title>Mdown</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>

                <Navbar></Navbar>

                <div className="pb-12">
                    <section className="pb-10">
                        <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                            <div className='min-h-screen prose-base prose-a:text-blue-700 prose-a:underline px-10 mt-10'>
                                <p className=''>در این صفحه قرار است آموزش مارک‌داون به زبان فارسی قرار گیرد و در آینده تکمیل می‌شود. برای مطالعه در مورد مارک‌داون می‌توانید <a href='https://www.markdownguide.org/'>به این سایت</a> مراجعه کنید یا در اینترنت به صورت فارسی یا انگلیسی جستجو کنید.</p>
                                <p className=''>اگر پیشنهادی دارید یا آموزشی را پیشنهاد می‌دهید می‌توانید به work.taleghani بر روی جی‌میل ایمیل کنید.</p>
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </>
    )
}
